version: "3.8"

services:
  db:
    container_name: postgresql
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/
    restart: always
    environment:
      - POSTGRES_DB=support-email
      - POSTGRES_USER=dizinnes
      - POSTGRES_PASSWORD=dizinnes
      - PGDATA=/var/lib/pgadmin
    ports:
      - "5432:5432"

volumes:
  postgres_data: